# Generated by Django 5.1.3 on 2024-12-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_count", models.IntegerField(default=2)),
                ("player_dice_game_map", models.JSONField(default=dict)),
            ],
        ),
    ]
